version: '3'
services:

  mariadb:
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    networks:
      - ContNet

  wordpress:
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    build: ./requirements/wordpress
    networks:
      - ContNet


  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - ContNet


networks:
  ContNet:
    driver: bridge

volumes:

  mariadb_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/aoueldma/data/dt_volume/
  wordpress_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/aoueldma/data/wd_volume/