# services:
#   data_base:
#     build: ./Maria
#   word_press:
#     build: ./WordPress
#     environment:
#       DB_DB_CONT_NAME: inception-data_base-1
#       DB_DATABASE: my_database
#       DB_USER: my_database_user
#       DB_PASSWORD: password123
#   web_sever:
#     build: ./nginx
#     ports:
#       - "8080:400"

version: '3'
services:
  mariadb:
    container_name: mariadb
    volumes:
      - dt_v:/var/lib/mysql
    build: ./Maria
    networks:
      - bridgeeeee
    environment:
      DB_NAME: my_database
      DB_USER: my_database_user
      DB_PASS: password123
      DB_CONT_NAME: mariadb
  wordpress:
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wd_v:/var/www/html
    build: ./WordPress
    networks:
      - bridgeeeee
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wd_v:/var/www/html
    build: ./nginx
    ports:
      - "1069:8080"
    networks:
      - bridgeeeee
networks:
  bridgeeeee:
    driver: bridge

volumes:
  wd_v:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /Users/enima/Desktop/inception/wd_volume/
  dt_v:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /Users/enima/Desktop/inception/dt_volume/

