# services:
#   data_base:
#     build: ./Maria
#   word_press:
#     build: ./WordPress
#     environment:
#       DB_DB_CONT_NAME: inception-data_base-1
#       DB_DATABASE: my_database
#       DB_USER: my_database_user
#       DB_PASSWORD: password123
#   web_sever:
#     build: ./nginx
#     ports:
#       - "8080:400"

version: '3'
services:
  data_base:
    volumes:
      - dt_v:/var/lib/mysql
    build: ./Maria
    networks:
      - bridge
  word_press:
    volumes:
      - wd_v:/var/www/html
    build: ./WordPress
    environment:
      DB_NAME: my_database
      DB_USER: my_database_user
      DB_PASS: password123
      DB_CONT_NAME: inception-data_base-1:3306
    networks:
      - bridge
  web_sever:
    volumes:
      - wd_v:/var/www/html
    build: ./nginx
    ports:
      - "1069:8080"
    networks:
      - bridge
networks:
  bridge:
volumes:
  wd_v:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /Users/enima/Desktop/inception/wd_volume/
  dt_v:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /Users/enima/Desktop/inception/dt_volume/

