# services:
#   data_base:
#     build: ./Maria
#   word_press:
#     build: ./WordPress
#     environment:
#       DB_DB_CONT_NAME: inception-data_base-1
#       DB_DATABASE: my_database
#       DB_USER: my_database_user
#       DB_PASSWORD: password123
#   web_sever:
#     build: ./nginx
#     ports:
#       - "8080:400"

version: '3'
services:

  mariadb:
    container_name: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    build: ./Maria
    networks:
      - bridgeeeee
    env_file: .env

  
  wordpress:
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    build: ./WordPress
    networks:
      - bridgeeeee



  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    build: ./nginx
    ports:
      - "1069:8080"
    networks:
      - bridgeeeee



networks:
  bridgeeeee:
    driver: bridge

volumes:

  mariadb_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /Users/enima/Desktop/inception/dt_volume
  wordpress_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /Users/enima/Desktop/inception/wd_volume
