FROM debian

# Copy the script into the container
COPY script.sh /usr/local/bin/script.sh

# Give execute permission to the script
RUN chmod +x /usr/local/bin/script.sh

# Run the script
CMD ["script.sh"]